"use client"
import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { SessionProvider, useSession } from "next-auth/react";

import { api } from "~/trpc/react";
import { TRPCReactProvider } from "~/trpc/react";
import Header from "./_components/Header";
import Sidebar from "./_components/Sidebar";

// export const metadata: Metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

// function AppShell({ children }: { children: React.ReactNode }) {
//   const { status } = useSession();

//   return (
//     <div className="h-screen flex flex-col">
//       <Header />
//       <div className="flex flex-1">
//         {status === "authenticated" && <Sidebar />}
//         <main className="flex-1">{children}</main>
//       </div>
//     </div>
//   );
// }

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
          <SessionProvider>
            <TRPCReactProvider>
              <Header/>
              {children}
            </TRPCReactProvider>
            {/* </TRPCReactProvider> */}
          </SessionProvider>
      </body>
    </html>
  );
}
